import os, sys, pickle
import datetime as dt
import numpy as np
from concurrent.futures import ProcessPoolExecutor, as_completed
from functools import partial
import multiprocessing

from lwcc_counter import edges2lwcc


def _worker_chunk(model, all_nodes, verbose, worker_id, n_chunk, seed):
    """Worker function executed in a separate process.

    Performs `n_chunk` independent sampling iterations:
    for each iteration, draws a synthetic network from the model (`sol.sample()`),
    computes its LWCC size, and accumulates the results.

    Each worker seeds numpy with its own independent random seed to ensure
    that samples generated by different workers are statistically independent
    (no shifted-sequence artifacts).

    Parameters
    ----------
    model : model object
        Fitted model exposing a `.sample()` method.
    all_nodes : array-like
        Ordered array of node IDs used to remap sampled edge indices.
    verbose : bool
        If True, prints a timestamped message at every 20% of the chunk.
    worker_id : int
        Index of this worker, used in verbose messages.
    n_chunk : int
        Number of sampling iterations assigned to this worker.
    seed : int
        Random seed for numpy, drawn independently per worker.

    Returns
    -------
    sizes_list : list of int
        One LWCC size per iteration.
    """
    np.random.seed(seed)
    sizes_list = []
    # Compute the iteration indices at which to print progress (every 20%).
    milestones = set(max(1, round(n_chunk * p / 5)) for p in range(1, 6))
    for i in range(n_chunk):
        sampled_wel = model.sample()
        # give the right node labels to the sampled edge list (model.sample() returns edges with node indices, we need to map them back to actual node IDs)
        sampled_wel = [(all_nodes[edge[0]], all_nodes[edge[1]], edge[2]) for edge in sampled_wel]
        sizes_list.append(lwcc_size_from_el(sampled_wel))
        if verbose and (i + 1) in milestones:
            pct = round((i + 1) / n_chunk * 100)
            print(f'[{dt.datetime.now():%Y-%m-%d %H:%M:%S}] Worker {worker_id}: {pct}% ({i + 1}/{n_chunk})', flush=True)
    return sizes_list


def validate(weighted_el, model, n_runs, n_workers=None, verbose=False):
    """Perform a Monte Carlo hypothesis test of the LWCC size.

    Compares the empirical LWCC size against a null distribution generated
    by sampling `n_runs` synthetic networks from the fitted model.

    The p-value is estimated as the two-tailed fraction of simulated networks
    whose LWCC size is as extreme as or more extreme than the observed value.

    The loop over simulated networks is parallelised across `n_workers`
    independent processes via ProcessPoolExecutor. Each worker receives a
    contiguous chunk of iterations and an independently drawn random seed,
    so results are statistically equivalent to a sequential run.

    Parameters
    ----------
    weighted_el : list of (source, target, weight) triples
        The empirical weighted edge list.
    model : model object
        Fitted model exposing a `.sample()` method (must be picklable so it
        can be sent to subprocess workers).
    n_runs : int
        Total number of Monte Carlo samples.
    n_workers : int or None
        Number of parallel worker processes. Defaults to the number of
        logical CPU cores. Capped at n_runs if n_runs < n_workers.
    verbose : bool
        If True, each worker prints a timestamped message every 20% of its
        assigned iterations.

    Returns
    -------
    lwcc_dict : dict
        - 'obs'          : observed LWCC size.
        - 'count_sample' : list of sampled LWCC sizes, one per simulated network.
        - 'p_value'      : estimated two-tailed p-value.
    """
    # Get all nodes from the empirical edge list to ensure consistent node indexing in samples
    all_nodes = np.concatenate((weighted_el['source_id'], weighted_el['target_id']))
    all_nodes = np.unique(all_nodes)

    # --- Empirical LWCC size ---
    emp_lwcc_size = lwcc_size_from_el(weighted_el)

    # --- Parallelisation setup ---
    if n_workers is None:
        n_workers = multiprocessing.cpu_count()
    n_workers = min(n_workers, n_runs)

    # Distribute n_runs as evenly as possible across workers:
    # workers with index < remainder get one extra iteration.
    base, remainder = divmod(n_runs, n_workers)
    chunks = [base + 1 if i < remainder else base for i in range(n_workers)]

    # Draw fully independent seeds for each worker (not derived from a common base)
    # to avoid correlated pseudo-random sequences across processes.
    seeds = np.random.randint(0, 2**31, size=n_workers).tolist()

    # Bind the fixed arguments once; each worker only needs (worker_id, n_chunk, seed).
    worker = partial(_worker_chunk, model, all_nodes, verbose)
    task_args = list(zip(chunks, seeds))

    futures = [None] * n_workers
    with ProcessPoolExecutor(max_workers=n_workers) as executor:
        fut_map = {executor.submit(worker, i, n_chunk, seed): (i, n_chunk)
                   for i, (n_chunk, seed) in enumerate(task_args)}
        for fut in as_completed(fut_map):
            idx, _ = fut_map[fut]
            futures[idx] = fut.result()

    # --- Aggregate results from all workers ---
    samples = []
    for sizes_list in futures:
        samples.extend(sizes_list)

    # --- Compute two-tailed p-value ---
    count_ge = sum(1 for x in samples if x >= emp_lwcc_size)
    count_le = sum(1 for x in samples if x <= emp_lwcc_size)
    return {
        'obs':          emp_lwcc_size,
        'count_sample': samples,
        'p_value':      min(1.0, 2 * min(count_ge, count_le) / n_runs),
    }


def lwcc_size_from_el(weighted_el):
    """Compute the size of the Largest Weakly Connected Component (LWCC).

    Parameters
    ----------
    weighted_el : list of (source, target, weight) triples
        Weighted directed edge list. Weights are ignored; only topology matters.

    Returns
    -------
    lwcc_size : int
        Number of nodes in the LWCC.
    """
    topo_el = [(s, t) for s, t, w in weighted_el]
    return edges2lwcc(topo_el)
