import os, sys, pickle
import datetime as dt
import numpy as np
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
from functools import partial
from tqdm import tqdm
import multiprocessing

from bowtie import edges2bowtie


def _worker_chunk(args):
    """Worker function executed in a separate process.

    Performs `n_chunk` independent sampling iterations:
    for each iteration, draws a synthetic network from the model (`sol.sample()`),
    computes its bowtie structure, and accumulates the results.

    Each worker seeds numpy with its own independent random seed to ensure
    that samples generated by different workers are statistically independent
    (no shifted-sequence artifacts).

    Parameters
    ----------
    args : tuple
        (model, n_chunk, seed)
        - model   : fitted model object exposing a `.sample()` method that returns
                    a weighted edge list as a list of (source, target, weight) triples.
        - n_chunk : number of sampling iterations assigned to this worker.
        - seed    : integer random seed for numpy, drawn independently per worker.

    Returns
    -------
    blocks_list : list of dict
        One dict per iteration mapping bowtie block label -> node count.
    fluxes_list : list of dict
        One dict per iteration mapping (block_src, block_tgt) -> total weight flux.
    """
    model, all_nodes, emp_bowtie_dict, n_chunk, seed = args
    np.random.seed(seed)
    blocks_list = []
    fluxes_list = []
    for _ in range(n_chunk):
        sampled_wel = model.sample()
        # give the right node labels to the sampled edge list (model.sample() returns edges with node indices, we need to map them back to actual node IDs)
        sampled_wel=[(all_nodes[edge[0]], all_nodes[edge[1]], edge[2]) for edge in sampled_wel]
        sim_blocks, sim_fluxes, _ = block_and_fluxes(sampled_wel, original_bowtie_dict=emp_bowtie_dict)
        blocks_list.append(dict(sim_blocks))
        fluxes_list.append(dict(sim_fluxes))
    return blocks_list, fluxes_list


def validate(weighted_el, model, n_runs, n_workers=None):
    """Perform a Monte Carlo hypothesis test of the bowtie structure.

    Compares the empirical bowtie block sizes and inter-block weight fluxes
    against a null distribution generated by sampling `n_runs` synthetic
    networks from the fitted model `sol`.

    For each block and each inter-block flux, the p-value is estimated as
    the fraction of simulated networks whose value is >= the observed value
    (one-sided, upper-tail test).

    The loop over simulated networks is parallelised across `n_workers`
    independent processes via ProcessPoolExecutor. Each worker receives a
    contiguous chunk of iterations and an independently drawn random seed,
    so results are statistically equivalent to a sequential run.

    Parameters
    ----------
    weighted_el : list of (source, target, weight) triples
        The empirical weighted edge list.
    model : model object
        Fitted model exposing a `.sample()` method (must be picklable so it
        can be sent to subprocess workers).
    n_runs : int
        Total number of Monte Carlo samples.
    n_workers : int or None
        Number of parallel worker processes. Defaults to the number of
        logical CPU cores. Capped at n_runs if n_runs < n_workers.

    Returns
    -------
    block_dict : dict
        Keys are bowtie block labels. Each value is a dict with:
        - 'obs'     : observed node count in that block.
        - 'p_value' : estimated upper-tail p-value.
    flux_dict : dict
        Keys are (block_src, block_tgt) pairs. Each value is a dict with:
        - 'obs'     : observed total weight flux between the two blocks.
        - 'p_value' : estimated upper-tail p-value.
    """
    # Get all nodes from the empirical edge list to ensure consistent node indexing in samples
    all_nodes=np.concatenate((weighted_el['source_id'], weighted_el['target_id']))
    all_nodes=np.unique(all_nodes)
    
    # --- Empirical bowtie ---
    emp_bowtie_blocks, emp_bowtie_fluxes, emp_bowtie_dict = block_and_fluxes(weighted_el)

    # Initialise result containers with observed values and zero p-values
    block_dict = defaultdict(dict)
    flux_dict  = defaultdict(dict)
    for block, dim_block in emp_bowtie_blocks.items():
        block_dict[block]['obs']     = dim_block
        block_dict[block]['p_value'] = 0

    for (block_s, block_t), flux in emp_bowtie_fluxes.items():
        flux_dict[(block_s, block_t)]['obs']     = flux
        flux_dict[(block_s, block_t)]['p_value'] = 0

    # --- Parallelisation setup ---
    if n_workers is None:
        n_workers = multiprocessing.cpu_count()
    n_workers = min(n_workers, n_runs)

    # Distribute n_runs as evenly as possible across workers:
    # workers with index < remainder get one extra iteration.
    base, remainder = divmod(n_runs, n_workers)
    chunks = [base + 1 if i < remainder else base for i in range(n_workers)]

    # Draw fully independent seeds for each worker (not derived from a common base)
    # to avoid correlated pseudo-random sequences across processes.
    seeds = np.random.randint(0, 2**31, size=n_workers).tolist()

    # Bind the fixed arguments once; each worker only needs (n_chunk, seed).
    worker = partial(_worker_chunk, model, all_nodes, emp_bowtie_dict)
    task_args = list(zip(chunks, seeds))

    # Launch workers and collect results in order, updating the progress bar
    # as each worker completes (unit = individual sampling iterations).
    futures = [None] * n_workers
    with ProcessPoolExecutor(max_workers=n_workers) as executor:
        fut_map = {executor.submit(worker, n_chunk, seed): (i, n_chunk)
                   for i, (n_chunk, seed) in enumerate(task_args)}
        with tqdm(total=n_runs, desc="Sampling", unit="run") as pbar:
            for fut in as_completed(fut_map):
                idx, chunk_size = fut_map[fut]
                futures[idx] = fut.result()
                pbar.update(chunk_size)

    # --- Aggregate results from all workers ---
    for blocks_list, fluxes_list, bts in futures:
        # Update block p-values
        for sim_bowtie_blocks in blocks_list:
            for block, dim_block in sim_bowtie_blocks.items():
                if dim_block >= block_dict[block]['obs']:
                    block_dict[block]['p_value'] += 1 / n_runs
        # Update flux p-values
        for sim_bowtie_fluxes in fluxes_list:
            for (block_s, block_t), flux in sim_bowtie_fluxes.items():
                if flux >= flux_dict[(block_s, block_t)]['obs']:
                    flux_dict[(block_s, block_t)]['p_value'] += 1 / n_runs

    return block_dict, flux_dict


def block_and_fluxes(weighted_el, original_bowtie_dict=None):
    """Extract the bowtie structure of a weighted directed network.

    Assigns each node to a bowtie block (SCC, IN, OUT, TUBE, OTHER, …)
    using `edges2bowtie`, then counts how many nodes belong to each block
    and how much total weight flows between each pair of blocks.

    Parameters
    ----------
    weighted_el : list of (source, target, weight) triples
        Weighted directed edge list. The `weight` field is used only for
        computing inter-block fluxes; topology is determined by (source, target).

    Returns
    -------
    bowtie_counts : defaultdict(int)
        Maps each bowtie block label to the number of nodes in that block.
    bowtie_fluxes : defaultdict(int)
        Maps each (block_src, block_tgt) pair to the total edge weight
        flowing from block_src to block_tgt.
    """
    # Strip weights to get the bare directed topology required by edges2bowtie
    topo_el = [(s, t) for s, t, w in weighted_el]
    bowtie_dict = edges2bowtie(topo_el)   # node -> block label

    # Count nodes per block
    bowtie_counts = defaultdict(int)
    for node, block in bowtie_dict.items():
        bowtie_counts[block] += 1

    if original_bowtie_dict is None:
        original_bowtie_dict = bowtie_dict

    # Sum edge weights for each directed pair of blocks
    bowtie_fluxes = defaultdict(int)
    for s, t, w in weighted_el:
        block_s = original_bowtie_dict[s]
        block_t = original_bowtie_dict[t]
        bowtie_fluxes[(block_s, block_t)] += w

    return bowtie_counts, bowtie_fluxes, bowtie_dict
